# Keycloak configuration values
auth:
  adminUser: admin
  adminPassword: admin  # Change for production!

# Database configuration
database:
  type: postgresql
  host: keycloak-postgresql
  port: 5432
  database: bitnami_keycloak
  username: bn_keycloak
  password: bn_keycloak

service:
  type: ClusterIP

# Configure database
postgresql:
  enabled: true
  auth:
    username: bn_keycloak
    password: bn_keycloak  # Change for production!
    database: bitnami_keycloak
    postgresPassword: postgres  # Root password

# Configure Istio integration
proxy: edge

# Use appropriate resource limits for development
resources:
  limits:
    memory: 1Gi
    cpu: 1000m
  requests:
    memory: 512Mi
    cpu: 250m

# For development, we can reduce replicas
replicaCount: 1

# Specify Docker Hub registry directly
image:
  registry: docker.io
  repository: bitnami/keycloak
  
postgresql:
  image:
    registry: docker.io
    repository: bitnami/postgresql
